---
- name: Update repositories cache (apt)
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "apt"

- name: Update repositories cache (pacman)
  pacman:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "pacman"

- name: Install required packages (apt)
  apt:
    name: ssh
  notify: Restart sshd
  when: ansible_pkg_mgr == "apt"

- name: Install required packages (pacman)
  pacman:
    name: openssh
  notify: Restart sshd
  when: ansible_pkg_mgr == "pacman"

- import_tasks: config.yml
- import_tasks: moduli.yml
